name: Release new APpForge version
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release-maven-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Import GPG signing key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MAVEN_SIGNING_KEY }}
          passphrase: ${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }}
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: maven-central-release
          server-username: vdjurovic
          server-password: ${{ secrets.MVN_CENTRAL_PASSWORD }}
      - run: | 
          echo "Current directory: $PWD"
      - name: Release to Maven repo"
        run: |
          export VERSION=$(./cicd/version.sh)
          echo "Version to set: $VERSION"
          mvn -Dgpg.keyname=${{ secrets.GPG_KEY_NAME }} -Dgpg.passphrase=${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }} \
              -DreleaseVersion=$VERSION -Dtag=v$VERSION  release:prepare release:perform

